"""Nueva migración

Revision ID: ac740cd9204a
Revises: 4060643292e6
Create Date: 2025-07-14 23:03:49.938314

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac740cd9204a'
down_revision = '4060643292e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.alter_column('order',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_jti', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_jti')

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.alter_column('order',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
